pipeline:
  backup-mongo-data:
    image: alpine
    commands:
      - apk update && apk add --no-cache openssh sshpass
      - export SSHPASS=Cj57AQCn
      - sshpass -e ssh -o StrictHostKeyChecking=no root@vps135621.vps.ovh.ca 'tar -czvf /home/ubuntu/mongo.tar.gz /home/ubuntu/ambientes/dev/data/mongo'
  copying-mongo-data:
    image: alpine
    commands:
      - apk update && apk add --no-cache openssh sshpass
      - cd /workspace
      - rm -rf /workspace/*
      - export SSHPASS=Cj57AQCn
      - sshpass -e scp -o StrictHostKeyChecking=no root@vps135621.vps.ovh.ca:/home/ubuntu/mongo.tar.gz mongo.tar.gz 
      - tar -xzvf mongo.tar.gz
      - ls
      - mv home/ubuntu/ambientes/dev/data/mongo mongo-v
      - mv mongo-v/* .
      - rm -rf home
      - ls
      - sshpass -e ssh -o StrictHostKeyChecking=no root@vps135621.vps.ovh.ca 'rm -rf /home/ubuntu/mongo.tar.gz'
    volumes:
      - workspace-drone-mongo:/workspace
  mongo:
   image: mongo:3.4
   volumes:
      - workspace-drone-mongo:/data/db
   detach: true
  build:
    image: hgarcio/ubuntu-node-java
    commands:
     - chmod +x mvnw
     - ./mvnw clean install
     - ./mvnw package
     - ./mvnw package -Dspring.profiles.active=test
  docker:
    image: plugins/docker
    username: hgarcio
    password: h1o2g3o4o5o6
    auto_tag: true
    repo: hgarcio/mspostshatcc
    dockerfile: Dockerfile
    tags: latest