language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
addons:
    apt:
        packages:
            - sshpass
before_install:
  - java -version
  - chmod +x mvnw
script:
  - ./mvnw clean
  - ./mvnw package -Pprod -DskipTests
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
after_success:
    - cd target
    - tar -cf msposts.tgz *.war
    - export SSHPASS=$DEPLOY_PASS
    - sshpass -e scp -o StrictHostKeyChecking=no msposts.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/$TRAVIS_BRANCH/deploy/msposts
    - test $TRAVIS_BRANCH != "dev" && sshpass -e ssh -f -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/$TRAVIS_BRANCH/deploy/msposts/deploy.sh