version: '2'
services:
    mspostshatcc-mongodb:
        container_name: mspostshatcc-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/msPostsHatcc/mongodb/:/data/db/
